MvcApp/Models/Blog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO;
using System.Linq;
using System.Web;
using System.Xml.Serialization;

namespace MvcApplication1.Models
{
	public class Blog
	{
		[Key]
		public int Id { get; set; }
		public DateTime DateTime { get; set; }	
		public string Tresc { get; set; }

	}
}

MvcApp/Models/BlogSet.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Web;

namespace MvcApplication1.Models
{
	public class BlogSet : DbContext
	{
		public DbSet<Blog> Blog { get; set; }

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
			modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
		}
	}
}

MvcApp/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;

namespace MvcApp.Controllers
{
	public class BlogController : Controller
	{
		private readonly BlogSet _ctx = new BlogSet();

		public ActionResult Index()
		{
			var model = _ctx.Blog.ToList();
				return View(model);
		}

		[HttpPost]
		public ActionResult Add(string tresc)
		{
			if (ModelState.IsValid)
			{
				_ctx.Blog.Add(new Blog() {DateTime = DateTime.Now, Tresc = tresc});
				_ctx.SaveChanges();
			}

			return RedirectToAction("Index");
		}

		public ActionResult Delete(int id)
		{
			var blog = _ctx.Blog.SingleOrDefault(s => s.Id == id);
			_ctx.Blog.Remove(blog);
			_ctx.SaveChanges();

			return RedirectToAction("Index");
		}
	}
}

MvcApp/Views/Blog/Index.cshtml
@model List<MvcApplication1.Models.Blog>

@{
    Layout = null;
}

<table>
    <tr>
        <th>data</th>
        <th>treść</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.DateTime</td>
            <td>@item.Tresc</td>
            <td>@Html.ActionLink("Delete", "Delete",
                    new {id = item.Id},
                    new {onclick = "return confirm('Czy na pewno chcesz usunąć ten wpis?');"})
            </td>
        </tr>
    }
</table>

<div>
    @using (Html.BeginForm("Add", "Blog"))
    {
        
        @Html.TextArea("Tresc")
        <br />
        <input type="submit" value="Dodaj wpis" />
    }
</div>